---
title: "Data Analysis"
output: html_document
date: "2024-03-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(DBI)
library(RSQLite)
library(readr)
library(dplyr)
library(plotly)
```

## Connect to database

```{r}
connect <- dbConnect(RSQLite::SQLite(), "database.db")
```

1.  Top 5 Suppliers (quantity of products supplied/ stock on hand)

```{r}
product <- RSQLite::dbGetQuery(connect,'SELECT * FROM PRODUCT')
top_suppliers<- product %>% group_by(supplier_id) %>% summarise(quantity=sum(stock_on_hand))

```

```{r}
top_5_suppliers <- top_suppliers %>% 
  arrange(desc(quantity)) %>% 
  slice(1:5)

# Create a bar plot using Plotly
plot_ly(data = top_5_suppliers, x = ~supplier_id, y = ~quantity, type = 'bar', 
        marker = list(color = 'skyblue')) %>%
  layout(title = "Top 5 Suppliers by Stock",
         xaxis = list(title = "Supplier ID"),
         yaxis = list(title = "Stock on Hand"),
         showlegend = FALSE)
```

2.  Top 10 products based on the revenue generated

```{r}
order_item <- RSQLite::dbGetQuery(connect,'SELECT * FROM ORDER_ITEM')
order_detail <- RSQLite::dbGetQuery(connect,'SELECT * FROM ORDER_DETAIL')
discount <- RSQLite::dbGetQuery(connect,'SELECT * FROM DISCOUNT')

profit_data <- order_item %>%
  inner_join(order_detail, by = "order_id") %>% # Assuming order_id is the common key
  filter(order_status != "Cancelled") %>%
  inner_join(product, by = "product_id") %>%
  left_join(discount, by = c("promo_code" = "promo_code")) %>%
  mutate(
    discount_percentage = ifelse(is.na(discount_percent), 0, discount_percent), 
    total_profit = (order_quantity * unit_price) * (1 - discount_percentage / 100)
  ) %>%
  group_by(product_id, product_name) %>%
  summarise(
    total_profit = sum(total_profit), 
    .groups = 'drop'
  ) %>%
  arrange(desc(total_profit))

```

```{r}

# Selecting the top 10 profitable products
top_10_profit_data <- head(profit_data, 10)


# graphing the results
ggplot(top_10_profit_data, aes(x = reorder(product_id, total_profit), y = total_profit, fill = product_name)) +
  geom_bar(stat = "identity") +
  scale_fill_discrete(name = "product Name") + 
  labs(title = "Top 10 Profitable products", x = "Product ID", y = "Total Profit") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.title = element_text(size = 12), 
        legend.text = element_text(size = 10), 
        plot.title = element_text(hjust = 0.5)) 

```

3.  Comparing the effectiveness of each Advertisement Type

```{r}
# Joining Product with advertise_in and advertisement to get advertisement details
#test
advertise_in <- RSQLite::dbGetQuery(connect,'SELECT * FROM ADVERTISE_IN')
advertisement <- RSQLite::dbGetQuery(connect,'SELECT * FROM ADVERTISEMENT')

advertisement_data <- product %>%
  inner_join(advertise_in, by = "product_id") %>%
  inner_join(advertisement, by = "ad_id") %>%
  group_by(product_id, product_name, ad_place) %>%
  summarise(
    total_frequency = sum(ad_frequency), # Sum the total frequency of ads for each ad place
    .groups = 'drop' )


# Joining product with order to get the number of sales per product
number_of_sales <- product %>%
  inner_join(order_item, by = "product_id") %>%
  group_by(product_id, product_name) %>%
  summarise(sales_count = n(), .groups = 'drop')

# Note: Each product is being sold twice.
# Note: Remove Category fee 
# Note: Product table: main category id column empty

merged_data <- merge(number_of_sales, advertisement_data, by = c("product_id", "product_name"))

```

```{r}
# Analyzing which ad place is most effective by calculating a ratio of total sales to total ad frequency
effective_ad_type <- merged_data %>%
  group_by(ad_place) %>%
  summarise( total_sales = sum(sales_count), 
    total_frequency = sum(total_frequency), .groups = 'drop') %>%
  mutate( effectiveness = total_sales / total_frequency) %>%
  arrange(desc(effectiveness))

```

```{r}

ggplot(effective_ad_type, aes(x = ad_place, y = effectiveness, fill = ad_place)) +
  geom_col(show.legend = FALSE, width = 0.5) + # Adjust bar width here
  scale_fill_brewer(palette = "Paired") + # Use a more appealing color palette
  labs(title = "Effectiveness of Advertisement Types", 
       x = "Ad Place", 
       y = "Total Sales / Total Frequency") +
  theme_minimal(base_size = 14) + # Increase base text size for better readability
  theme(plot.title = element_text(hjust = 0.5, size = 20), # Center and style title
        axis.title = element_text(size = 16), # Style axis titles
        axis.text = element_text(size = 12), # Style axis texts
        panel.grid.major = element_blank(), # Remove major grid lines
        panel.grid.minor = element_blank(), # Remove minor grid lines
        panel.background = element_rect(fill = "white", colour = "grey50")) # Style panel background

```

4.  Average Review for each category

```{r}
category <- RSQLite::dbGetQuery(connect,'SELECT * FROM CATEGORY')

# Join product_df with category_df to include category names
product_with_category <- product %>%
  inner_join(category, by = "category_id")


avg_rating_by_category <- product_with_category %>%
  group_by(category_id, category_name) %>%
  summarise(Average_Rating = round(mean(product_rating, na.rm = TRUE),2), .groups = 'drop') %>%
  arrange(category_id)

print(avg_rating_by_category)

```

```{r}

# Add a cumulative sum of Average_Rating to calculate position for labels
avg_rating_by_category <- avg_rating_by_category[order(-avg_rating_by_category$Average_Rating), ]

# Define your custom color palette
custom_colors <- c("#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd", "#8c564b")

ggplot(avg_rating_by_category, aes(x = Average_Rating, y = reorder(category_name, Average_Rating), fill = category_name)) +
  geom_bar(stat = "identity", color = "white") +
  geom_text(aes(label = sprintf("%.2f", Average_Rating), x = Average_Rating, y = category_name), 
            color = "black", size = 4, hjust = 2) +
  scale_fill_manual(values = custom_colors) +
  labs(fill = "Category Name",
       title = "Average Rating by Category") +
  theme_minimal() +
  theme(axis.line = element_blank(),
        axis.text = element_text(size = 9),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        panel.grid = element_blank(),
        plot.title = element_text(hjust = 0.5))

```

```{r}
library(lubridate)
time_period_sales<- RSQLite::dbGetQuery(connect,'SELECT ORDITM.order_id, order_quantity,order_date FROM ORDER_DETAIL ORDDET INNER JOIN ORDER_ITEM ORDITM ON ORDITM.order_id = ORDDET.order_id')

time_period_sales$order_date <- as.Date(time_period_sales$order_date, format="%d/%m/%Y")

time_period_sales$order_date_mnth_yr <- format(time_period_sales$order_date,'%Y/%m')

time_period_sales$order_date_mnth_yr <- factor(time_period_sales$order_date_mnth_yr, levels=c('2022/06','2022/07','2022/08','2022/09','2022/10','2022/11','2022/12','2023/01','2023/02','2023/03','2023/04','2023/05','2023/06','2023/07','2023/08','2023/09','2023/10','2023/11','2023/12'))

time_period_sales_group_by<- time_period_sales %>% group_by(order_date_mnth_yr)%>%summarise(quantity=sum(order_quantity))

(ggplot(time_period_sales_group_by, aes(x = order_date_mnth_yr, y = quantity,group=1)) +  geom_point()+geom_line()+xlab('Time Period(year/mpnth)')+ylab('Quantity Sold'))
```

```{r}
#salesvsregion
cust_order_join<- RSQLite::dbGetQuery(connect, 'SELECT city,order_quantity FROM ADDRESS ADR INNER JOIN ORDER_DETAIL ORDDET ON ADR.customer_id = ORDDET.customer_id INNER JOIN ORDER_ITEM ORDITM ON ORDDET.order_id = ORDITM.order_id')

#cust_order_join<- inner_join(Customer,Order,by="customer_id")

sales_per_region<- cust_order_join %>% group_by(city)%>%summarise(quantity=sum(order_quantity))

top_5_sales_per_region <- sales_per_region[order(-sales_per_region$quantity),]

top_5_sales_per_region <- head(top_5_sales_per_region,10)

ggplot1 <- ggplot(top_5_sales_per_region, aes(x = reorder(city,-quantity), y = quantity,fill=quantity)) +  geom_bar(stat='identity')+scale_fill_gradient(low = "lightblue", high = "darkblue")+ xlab('Top 10 cities where sales is maximum')+ylab('Quantity Sold')
```

```{r}
#revenuevsregion
library(gridExtra)
cust_order_product_join <-RSQLite::dbGetQuery(connect, 'SELECT city,order_quantity,unit_price FROM ADDRESS ADR INNER JOIN ORDER_DETAIL ORDDET ON ADR.customer_id = ORDDET.customer_id INNER JOIN ORDER_ITEM ORDITM ON ORDDET.order_id = ORDITM.order_id INNER JOIN PRODUCT PRD ON PRD.product_id = ORDITM.product_id')

#TEST

cust_order_product_join$revenue <-  cust_order_product_join$order_quantity*cust_order_product_join$unit_price

revenue_per_region <- cust_order_product_join %>% group_by(city) %>% summarise(rev= sum(revenue))

top_5_revenue_per_region <- revenue_per_region[order(-revenue_per_region$rev),]

top_5_revenue_per_region <- head(top_5_revenue_per_region,10)

revenue_per_product_region <- cust_order_product_join %>% group_by(city) %>% summarise(rev= sum(revenue))

ggplot2 <- ggplot(top_5_revenue_per_region, aes(x = reorder(city, -rev), y = rev,fill=rev)) +  geom_bar(stat='identity')+scale_fill_gradient(low = "lightblue", high = "darkblue")+xlab('Top 10 cities with the maximum revenue')+ylab('Revenue')

grid.arrange(ggplot1,ggplot2,nrow(1))
```
