---
title: "Schema"
output: html_document
date: "2024-03-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(DBI)
library(RSQLite)
```

## Connect to database

```{r}
connect <- dbConnect(RSQLite::SQLite(), "database.db")
```

## Create CUSTOMER Table

```{sql connection=connect}
CREATE TABLE CUSTOMER (
  customer_id VARCHAR(50) PRIMARY KEY, 
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  gender VARCHAR(10),
  customer_email VARCHAR(50) NOT NULL UNIQUE,
  customer_mobile VARCHAR(15) NOT NULL UNIQUE
);
```

## Create ADDRESS table

```{sql connection=connect}
CREATE TABLE ADDRESS (
  postcode VARCHAR(20) PRIMARY KEY, 
  customer_id INT NOT NULL,
  street VARCHAR(50) NOT NULL,
  city VARCHAR(100) NOT NULL,
  country VARCHAR(100) NOT NULL,
  FOREIGN KEY (customer_id) REFERENCES CUSTOMER (customer_id)
);
```

## Create PRODUCT table

```{sql connection=connect}
CREATE TABLE PRODUCT (
  product_id VARCHAR(50) PRIMARY KEY, 
  product_name VARCHAR(50) NOT NULL,
  product_description VARCHAR(50),
  product_rating DECIMAL(5,2),
  unit_price DECIMAL(10,2) NOT NULL,
  stock_on_hand INT NOT NULL,
  main_product_id INT,
  category_id INT NOT NULL,
  supplier_id INT NOT NULL,
  FOREIGN KEY (supplier_id) REFERENCES SUPPLIER (supplier_id),
  FOREIGN KEY (category_id) REFERENCES CATEGORY (category_id)
);
```

## Create DISCOUNT table

```{sql connection=connect}
CREATE TABLE DISCOUNT (
  promo_code VARCHAR(20) PRIMARY KEY, 
  discount_amount INT NOT NULL
);
```

## Create ORDER table for CUSTOMER-PRODUCT relationship

```{sql connection=connect}
CREATE TABLE ORDER_ITEM (
  order_id VARCHAR(50),
  product_id VARCHAR(50),
  order_quantity INT NOT NULL,
  PRIMARY KEY (order_id, product_id),
  FOREIGN KEY (order_id)   REFERENCES ORDER_DETAIL (order_id)
  FOREIGN KEY (product_id) REFERENCES PRODUCT (product_id)
);
```

```{sql connection=connect}
CREATE TABLE ORDER_DETAIL (
  order_id VARCHAR(50) PRIMARY KEY,
  customer_id VARCHAR(50), 
  order_date DATE NOT NULL,
  order_status VARCHAR(50) NOT NULL, 
  promo_code VARCHAR(20),
  payment_method TEXT NOT NULL,
  FOREIGN KEY (customer_id) REFERENCES CUSTOMER (customer_id),
  FOREIGN KEY (promo_code)  REFERENCES DISCOUNT (promo_code)
);
```

## Create ADVERTISEMENT table

```{sql connection=connect}
CREATE TABLE ADVERTISEMENT (
  ad_id VARCHAR(50) PRIMARY KEY, 
  ad_frequency INT NOT NULL,
  ad_place VARCHAR(50) NOT NULL,
  ad_price DECIMAL(10, 2) NOT NULL
);
```

## Create ADVERTISE_IN table for PRODUCT-ADVERTISEMENT relationship

```{sql connection=connect}
CREATE TABLE ADVERTISE_IN (
  product_id VARCHAR(50),
  ad_id VARCHAR(50),
  PRIMARY KEY (product_id, ad_id),
  FOREIGN KEY (product_id) REFERENCES PRODUCT (product_id),
  FOREIGN KEY (ad_id)      REFERENCES ADVERTISEMENTS (ad_id)
);
```

## Create SUPPLIER table

```{sql connection=connect}
CREATE TABLE SUPPLIER (
  supplier_id VARCHAR(50) PRIMARY KEY, 
  supplier_name VARCHAR(50) NOT NULL,
  supplier_email VARCHAR(50) NOT NULL,
  supplier_mobile VARCHAR(20) NOT NULL
);
```

## Create CATEGORY table

```{sql connection=connect}
CREATE TABLE CATEGORY (
  category_id VARCHAR(50) PRIMARY KEY, 
  category_name VARCHAR(50) NOT NULL,
  category_fee INT NOT NULL
);
```
