name: ETL workflow for group 3

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/lockfile') }}
          restore-keys: ${{ runner.os }}-r-

          
      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: Rscript -e 'install.packages(c("ggplot2", "dplyr", "readr", "RSQLite"))'

          
      - name: Delete database file
        run: del /Q database.db
      - name: Create database schema
        run: Rscript database_schema.R
      - name: Validate and load data into database
        run: Rscript data_validation_and_load.R
      - name: Run R analysis
        run: Rscript xxx.R


      - name: Add files
        run: |
          git config --global user.email "u5586227@live.warwick.ac.uk"
          git config --global user.name "5586227"
          git add --all figures/
      - name: Commit files
        run: git commit -m "Add visualization plot figure"          

          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ secrets.TOKEN}}
            branch: main
