name: ETL workflow for group 3

on:
  push:
    branches: [ main ]

jobs:
  install-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for skip install flag
        run: echo "${{ github.event.head_commit.message }}"
        id: skip-install
        continue-on-error: true

      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'

      - name: Cache R packages
        if: ${{ steps.skip-install.outputs.code == 0 && steps.cache.outputs.cache-hit != 'true' }}
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/lockfile') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Install packages
        if: ${{ steps.skip-install.outputs.code == 0 && steps.cache.outputs.cache-hit != 'true' }}
        run: R -e 'install.packages(c("DBI", "dplyr", "readr", "RSQLite", "plotly", "tidyr", "lubridate"), dependencies=TRUE, repos="https://cloud.r-project.org")'

  run-tests-and-data-processing:
    needs: [install-packages]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: Rscript test.R
      
      - name: Create database schema
        run: R database_schema.R

      - name: Validate and load data into database
        run: R data_validation_and_load.R

      - name: Data analysis
        run: R data_analysis.R

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.TOKEN}}
          branch: main